# # -*- coding: utf-8 -*-
# """Number_plate_DB.ipynb
#
# Automatically generated by Colab.
#
# Original file is located at
#     https://colab.research.google.com/drive/1ARV84uadyeSvi9VFKSEzJHLM1uV4kO4G
# """
#
import mysql.connector
from mysql.connector import Error


def create_server_connection(host_name, user_name, user_password):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection
def create_database(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Database created successfully")
    except Error as err:
        print(f"Error: '{err}'")
def create_db_connection(host_name, user_name, user_password, db_name):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            database=db_name
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        if cursor.with_rows:
            # If there are rows, fetch them
            print(cursor.fetchall())
        connection.commit()
        print("Query successful")
    except Error as err:
        print(f"Error: '{err}'")
    finally:
        cursor.close()  # Make sure to close the cursor regardless of success or error

def read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall()
        return result
    except Error as err:
        print(f"Error: '{err}'")


connection = create_server_connection("localhost", "root", "")
q="CREATE DATABASE numberplate1"
create_database(connection,q)

create_teacher_table = """
CREATE TABLE company_master (
  company_id             VARCHAR(40) NOT NULL,
  company_name           VARCHAR(40) NOT NULL,
  password               VARCHAR(40) NOT NULL,
  date_added             DATE,
  reset_token            VARCHAR(255),
  reset_token_expiration DATETIME,
  email_id               VARCHAR(255)

  );
 """

connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database
execute_query(connection, create_teacher_table)

pk="""
ALTER TABLE company_master
ADD PRIMARY KEY (company_id);
"""
connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database

execute_query(connection, pk)
create_teacher_table = """
CREATE TABLE numberplate1 (
  number_plate VARCHAR(40) NOT NULL,
  name VARCHAR(40) NOT NULL,
  companyid VARCHAR(10) NOT NULL,
  date_added DATE,
  phone_no VARCHAR(20)
  );
 """

connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database
execute_query(connection, create_teacher_table)

# insetnno = """
# INSERT INTO numberplate1 VALUES
# ('dl7cQ1939','Ram','TCS','2024-02-15','4561123544'),
# ('mh02fe3920','Laxman','Infosys','2024-02-15','4458615477');
# """
# execute_query(connection, insetnno)
# update = """
#  UPDATE numberplate1
#  SET in_out = '0'
#  WHERE name = 'Ram';
#  """

# connection = create_db_connection("localhost", "root", '1234', 'numberplate1')
# execute_query(connection, update)
# a="""
# ALTER TABLE numberplate1 ADD in_out VARCHAR(1) DEFAULT 0;
# """

# execute_query(connection, a)

create_teacher_table = """
CREATE TABLE company_master (
  company_id             VARCHAR(40) NOT NULL,
  company_name           VARCHAR(40) NOT NULL,
  password               VARCHAR(40) NOT NULL,
  date_added             DATE
  reset_token            VARCHAR(255),
  reset_token_expiration DATETIME,
  email_id               VARCHAR(255)

  );
 """

connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database
execute_query(connection, create_teacher_table)

pk="""
ALTER TABLE company_master
ADD PRIMARY KEY (company_id);
"""
connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database

execute_query(connection, pk)
pk="""
ALTER TABLE numberplate1
ADD PRIMARY KEY (number_plate);
"""
connection = create_db_connection("localhost", "root", "", "numberplate1") # Connect to the Database

execute_query(connection, pk)

insetnno = """
INSERT INTO numberplate1 (number_plate, name, companyid, date_added, phone_no) VALUES
('DL7C1939', 'Ram', 'TCS', '2024-02-15', '4561123544'),
('KA03AB1234', 'Amit', 'Wipro', '2024-02-15', '9988776655'),
('TN10CD5678', 'Sita', 'HCL', '2024-02-15', '8877665544'),
('AP09EF9012', 'Raj', 'Cognizant', '2024-02-15', '9988554477'),
('KL07GH3456', 'Sunil', 'Accenture', '2024-02-15', '7766554433'),
('MH01IJ7890', 'Preeti', 'IBM', '2024-02-15', '6655443322'),
('UP14JK1234', 'Asha', 'TCS', '2024-02-15', '5544332211'),
('DL3LM5678', 'Ravi', 'Infosys', '2024-02-15', '4433221100'),
('HR26MN9012', 'Neha', 'Wipro', '2024-02-15', '3322110099'),
('GJ01OP3456', 'Kiran', 'HCL', '2024-02-15', '2211009988'),
('RJ14QR7890', 'Vijay', 'Cognizant', '2024-02-15', '1100998877'),
('TN09ST1234', 'Pooja', 'Accenture', '2024-02-15', '9988776655'),
('PB02UV5678', 'Deepak', 'IBM', '2024-02-15', '8877665544'),
('KA01WX9012', 'Sanjay', 'TCS', '2024-02-15', '7766554433'),
('MH15YZ3456', 'Aarti', 'Infosys', '2024-02-15', '6655443322'),
('DL4AB7890', 'Mohan', 'Wipro', '2024-02-15', '5544332211'),
('UP16CD1234', 'Sonal', 'HCL', '2024-02-15', '4433221100'),
('BR12EF5678', 'Kavita', 'Cognizant', '2024-02-15', '3322110099'),
('JK03GH9012', 'Manish', 'Accenture', '2024-02-15', '2211009988'),
('HR20IJ3456', 'Rani', 'IBM', '2024-02-15', '1100998877'),
('GJ03KL7890', 'Arun', 'TCS', '2024-02-15', '9988776655');

"""
execute_query(connection, insetnno)

insetnno = """
INSERT INTO company_master (company_id, company_name, password, date_added, reset_token, reset_token_expiration, email_id)
VALUES ('001', 'Tech Innovations', 'pass123', '2023-01-01', 'abcdef', '2023-01-02 12:00:00', 'info@techinnovations.com');

INSERT INTO company_master (company_id, company_name, password, date_added, reset_token, reset_token_expiration, email_id)
VALUES ('002', 'Green Solutions', 'secure456', '2023-02-15', NULL, NULL, 'contact@greensolutions.com');

INSERT INTO company_master (company_id, company_name, password, date_added, reset_token, reset_token_expiration, email_id)
VALUES ('003', 'Data Analytics Ltd', 'data789', '2023-03-20', 'xyz123', '2023-03-21 12:00:00', 'support@datalytics.com');
"""

execute_query(connection, insetnno)



